### ISSUE TITLE
Overwriting function annotations

### ISSUE THREAD

**Issue by mmondelli** [End-to-end-provenance/rdt#1]
I'm using rdt to collect provenance data from a workflow that uses functions from a specific package. I've set `annotate.inside.functions = TRUE` and `save.debug = TRUE` when running `prov.init`, and also executed `prov.annotate.on()` (after `prov.init)`. However, I noticed that in the _/debug_ directory the annotated file is overwritten with each new function that is executed, instead of generating a file for each one or concatenating the annotations in the same file (also the file name remains _annotated-_)
Is there any way to overcome this issue? Thanks!

**Comment by blernermhc** [comment]
You might try using prov.run instead of prov.init/prov.quit.  So, put the commands you want to run inside an R file (omitting the prov.init and prov.quit lines) and then say:
```
prov.run(<your-R-file>, annotate.inside.functions = TRUE, save.debug = TRUE)
```
substituting in the name of your file for `<your-R-file>`.  You should then end up with one file in the debug directory named annotated-your-R-file.R that contains the full script with the annotations added.

The debug folder is primarily intended for us when debugging rdt itself.  Of course, you are welcome to look at it if you are curious, but it won't be helpful if you are trying to debug your own script.

Let me know how that goes.

**Comment by mmondelli** [comment]
It worked. I need to collect more detailed data from the functions, not recorded in the json file, so I thought that these debug files could help. Thank you again!

**Comment by blernermhc** [comment]
Great!
